export const tokens = {
  colors: {
    light: {
      primary: '#2F6B4F',
      secondary: '#7FB069',
      cta: '#F2A541',
      success: '#4C9F70',
      warning: '#F2C14E',
      error: '#D96C4B',
      bg: '#FBF7F0',
      surface: '#FFFFFF',
      text: '#37423B',
      textMuted: '#8A958C',
      pot: '#C96F4A',
      wilted: '#9FB7A8',
      water: '#7EC8E3',
      primarySoft: '#E6F0E9',
      ctaSoft: '#FDF0DC',
      border: '#E8E2D6',
    },
    dark: {
      primary: '#2F6B4F',
      secondary: '#7FB069',
      cta: '#F2A541',
      success: '#4C9F70',
      warning: '#F2C14E',
      error: '#D96C4B',
      bg: '#16201B',
      surface: '#1F2B25',
      text: '#EEF2EC',
      textMuted: '#8A958C',
      pot: '#C96F4A',
      wilted: '#9FB7A8',
      water: '#7EC8E3',
      primarySoft: '#E6F0E9',
      ctaSoft: '#FDF0DC',
      border: '#E8E2D6',
    },
  },
  radius: { card: '24px', button: '16px', chip: '999px', sheet: '28px' },
  layout: { grid: '8px', page: '20px' },
  typography: {
    display: {
      fontFamily: 'Nunito',
      fontWeight: '800',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    h1: {
      fontFamily: 'Nunito',
      fontWeight: '700',
      fontSize: 28,
      lineHeight: 34,
      letterSpacing: 0,
    },
    h2: {
      fontFamily: 'Nunito',
      fontWeight: '700',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    body: {
      fontFamily: 'Inter',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0,
    },
    bodyStrong: {
      fontFamily: 'Inter',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0,
    },
    button: {
      fontFamily: 'Inter',
      fontWeight: '600',
      fontSize: 15,
      lineHeight: 20,
      letterSpacing: 0,
    },
    caption: {
      fontFamily: 'Inter',
      fontWeight: '400',
      fontSize: 13,
      lineHeight: 18,
      letterSpacing: 0,
    },
    tag: {
      fontFamily: 'Inter',
      fontWeight: '600',
      fontSize: 11,
      lineHeight: 14,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
  },
};

export type ThemeName = keyof typeof tokens.colors;
